version: '3.8'

networks:
  hadoop_network:
    driver: bridge

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    networks:
      - hadoop_network
    ports:
      - "9870:9870"    # Web UI
      - "9000:9000"    # RPC
    environment:
      - CLUSTER_NAME=hadoop_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2G'
        reservations:
          cpus: '1.0'
          memory: '1G'

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    networks:
      - hadoop_network
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2G'
        reservations:
          cpus: '1.0'
          memory: '1G'

  app:
    image: openjdk:11
    container_name: app
    networks:
      - hadoop_network
    depends_on:
      - namenode
      - datanode
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-cp", "build/libs/shadow-all.jar", "lab4.buckzor110.App"]

volumes:
  hadoop_namenode:
  hadoop_datanode: